- README.md
Hey, @romulomourao 
I have added two websites which offer programming courses and two youtube playlists which offer ruby tutorials.
Please review the same.
Thanks!!
> Two websites and two playlists added for ruby

- README.md
I've added Codecademy and Grok Learning to the Websites list and two JavaScript YouTube courses to the YouTube list
> Add two websites and two JS playlists

- README.md
#7 Added multiple language support
> Added Portuguese title and rearranged the rest of the README

- README.md
Swift language tutorial added to youtube playlists. #7
> Update README.md to add Learn Swift playlist

- README.md
Quaddro added to portuguese websites #1
> Quaddro added to portuguese websites

- README.md
Free Code Camp website added #1
> Free Code Camp website

- README.md
Rodrigo Branas Javascript playlist added to portuguese list #1
> Javascript playlist added to portuguese list

- README.md
Added two playlist for python 3
> Python update #7 #2

- README.md
As referenced in #67, added some youtube channels (Amy Codes, Netflix UI Engineering, DevTips). Hope it helps!
> Adding Youtube channels

- README.md
Has multiple commits because my vim trailing white spaces plugins added unnecessary changes.
> Adds 2 Derek Banas

- README.md
> Add more YouTube channels

- README.md
Adding [EXLskills](https://exlskills.com/) to the list of websites
> Added EXLskills to websites

- README.md
Add Origamid(https://www.origamid.com/) website to Portuguese list
> Added Origamid website

- README.md
This is an awesome resource for beginners to experts who want to learn about all things related with Cloud infrastructure.
> Add "A Cloud Guru" as a resource

- README.md
Added Fabio Vedovelli to the Portuguese youtube channels list, and a NodeJS playlist
> Add Fabio Vedovelli channel and a playlist

- README.md
Site com cursos interessantes para crianças a partir dos 4 anos de idade
> Adicionado code studio

- README.md
Added HackerEarth to list of websites in English
> Added HackerEarth

- README.md
Add 
Design Patterns, React Native and Game development playlists
Cs50, Christopher Okhravi youtube channel
> add design patterns,react-native,game development playlist

- README.md
*adding YouTube Channel in Spanish
> Update README.md Issue #121

- README.md
#113 
A great site to learn to program, practice exercises and algorithms. Happy hacktoberfest!
> add spoj website

- README.md
Courses, podcasts, and other stuff.
> Adds FullCycle Developer

- README.md
[Programming with mosh , python course added] (https://www.youtube.com/watch?v=_uQrJ0TkZlc&t=11867s)
Issue: #152
> Programming with mosh python course added

- README.md
Added Dan Abramov's newest javascript course
> New JS course added

- README.md
Add YouTube channels for Auth0, Jason Lengstorf, and Sanity
> Add YouTube channels

- README.md
- new Java books
- new Java Youtube channels
- a few new icons
> + Java  #152 

- README.md
Add Python for Data Science and Analytics Tutorial Series Youtube Playlist
> Add Python tutorials YouTube playlist

- README.md
Add Unity game development ebook
> Add game development ebook
